spring:
#  application:
#    name: Job-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

#  config server
  config:
    import: optional:configserver:http://fedora:8080
  profiles:
    active: dev

server:
  port: 8082

#Eureka client configs
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#Resilience4J configs
resilience4j:
  circuitbreaker:
    instances:
      companyBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based
