spring:
  application:
    name: Job-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
server:
  port: 8082

