server:
  port: 8084

spring:
  application:
    name: Gateway-service
  config:
    name: Gateway-Service

#Gateway configs
  cloud:
    gateway:
      mvc:
        routes:
        - id: company_service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/companies/**
        - id: job_service
          uri: lb://JOB-SERVICE-DEV
          predicates:
            - Path=/jobs/**
        - id: review_service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/reviews/**

#Eureka client configs
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/

#Zipking configs
management:
  trace:
    sample:
      probability: 1.0


logging:
  level:
    root: info
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.RouteDefinitionLocator: INFO