company-service:
  url: http://company:8081
job-service:
  url: http://job:8082
review-service:
  url: http://review:8083

server:
  port: 8081
spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://postgres:5432/company
    username: postgres
    password: n930310@
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  #RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#Eureka client configs
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://servicereg:8761/eureka/

#Zipkin
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

