server:
  port: 8081
spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always