company-service:
  url: http://localhost:8081
job-service:
  url: http://localhost:8082
review-service:
  url: http://localhost:8083

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: postgres
    password: n930310@
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  #RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

#Eureka client configs
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0